name: Build tests

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libsdl2-dev gcc-multilib g++-multilib libfreetype6-dev libvulkan-dev
    - name: make
      run: |
        cd unixExample
        make

  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest
    - name: Create Build Environment
      shell: powershell
      run: cmake -E make_directory ${{github.workspace}}/win32Example/build
    - name: Configure CMake
      shell: powershell
      run: |
        cd win32Example
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
    - name: Build
      shell: powershell
      run: |
        cd win32Example
        cmake --build . --config Release --target test
